### ISSUE TITLE
Korean Translation Update

### ISSUE THREAD

**Issue by Kai-Z-JP** [Kai-Z-JP/ATSAssistMod#16]
ATSAssistMod.gui.IFTTTMaterial.211.0=一度のみ再生
ATSAssistMod.gui.IFTTTMaterial.211.1=音声名
ATSAssistMod.gui.IFTTTMaterial.211.2=半径

ATSAssistMod.gui.IFTTTMaterial.211.0=한 번만 재생
ATSAssistMod.gui.IFTTTMaterial.211.1=음성 이름
ATSAssistMod.gui.IFTTTMaterial.211.2=반경

Google翻訳でこうなりますが正しいでしょうか？
よろしくお願いします。
@PC28K

**Comment by PC28K** [comment]
はい　あってます

**Comment by Kai-Z-JP** [comment]
ありがとうございます。
