### ISSUE TITLE
距離基準を車両先頭にするをATC予告にも追加

### ISSUE THREAD

**Issue by SAPONIN9000** [Kai-Z-JP/ATSAssistMod#32]
速度制限予告(ATC)機能に距離基準を車両先頭にのチェックボックスを追加してほしいです。
(TASC停車位置予告機能にある距離基準を車両先頭にする設定をATCにも移植してほしいです)

**Comment by Kai-Z-JP** [comment]
おかのした

**Comment by Kai-Z-JP** [comment]
Done in a2841e4
