### ISSUE TITLE
保安装置ブロックに隣接しているブロックにRS信号が入力される

### ISSUE THREAD

**Issue by Saqliva** [Kai-Z-JP/ATSAssistMod#35]
1.4.1v13で発生
1.4.1v12では問題なし
これのおかげで装置の肥大化が起こってしまいました
恐らくProjectRedのワイヤーが貼り付くように不導体ブロックから導体ブロックにした影響だと思われ

**Comment by Saqliva** [comment]
不導体ブロックでProjectRedのワイヤーが貼り付くようにできない場合はクローズしてもらって大丈夫です

**Comment by Kai-Z-JP** [comment]
導体ブロックに再変更の予定はありません。

**Comment by Kai-Z-JP** [comment]
嘘ついたできたわ

**Comment by Saqliva** [comment]
最高
