### ISSUE TITLE
IFTTTのDataMap設定でボタンが変なとこにある

### ISSUE THREAD

**Issue by PC28K** [Kai-Z-JP/ATSAssistMod#39]
![l](https://user-images.githubusercontent.com/41824434/158069294-2403524e-2fbb-4db9-adee-a2cc1fde1e0a.png)

DataTypeにあるはずのボタンがKeyとValueの間にあります

**Comment by Kai-Z-JP** [comment]
https://github.com/Kai-Z-JP/ATSAssistMod/commit/09a846b4a828bf7536ad047c9ad3ff5f7e20c346 で修正しました
