### ISSUE TITLE
列車の進入方向による動作のON/OFF機能

### ISSUE THREAD

**Issue by MilkNum2** [Kai-Z-JP/ATSAssistMod#49]
単線における速度制限などの設定が簡単にできるように、片側から侵入した際は作動し、反対から侵入した際は作動しないというシステムがあればいいなと思い提案させていただきました

**Comment by Kai-Z-JP** [comment]
![image](https://github.com/Kai-Z-JP/ATSAssistMod/assets/42648535/8e304575-221f-4efa-a478-cc123b40e34e)
9a07066e で実装

**Comment by shinonnon** [comment]
素人質問で恐縮ですが、次のリリースで追加ということでしょうか？

**Comment by Kai-Z-JP** [comment]
左様でございます
