### ISSUE TITLE
IFTTTのSetBlockを設定中、未指定の値を含むものを削除しようとするとクラッシュする

### ISSUE THREAD

**Issue by hilot06** [Kai-Z-JP/ATSAssistMod#60]
SetBlockを設定中、入力欄のいずれかが未指定(空白)の状態で右側にあるマイナスボタンを押すとクラッシュしてゲームが終了します。

> The game crashed whilst updating screen events
> Error: java.lang.NumberFormatException: For input string: ""

というエラーのようです。
よろしくお願いします。

[クラッシュレポート](https://github.com/Kai-Z-JP/ATSAssistMod/files/12536629/crash-2023-09-06_20.04.18-client.txt)

**Comment by Kai-Z-JP** [comment]
242215cb で修正
