### ISSUE TITLE
単線でも使えるような機能がほしいです。

### ISSUE THREAD

**Issue by shinonnon** [Kai-Z-JP/ATSAssistMod#61]
1.12.2を使わせてもらってます。特定の方向の列車のみ地上子が反応するような機能を追加してほしいです。現在の状況だと単線でも上り列車用の地上子を、下り列車が踏んだら反応してしまい片方の方面の列車しか自動運転が使えないので、この列車はこの地上子を無視する・反応するといった選択ができる機能がほしいです。

**Comment by Kai-Z-JP** [comment]
#49 と同一
