### ISSUE TITLE
Auto Breakがオフになってもブレーキが働く

### ISSUE THREAD

**Issue by useop0311** [Kai-Z-JP/ATSAssistMod#67]
(Google翻訳を使用しました。)

セキュリティブロックを使用して制限速度を設定すると、自動ブレーキエントリを無効にしても自動的にブレーキが機能します。

**Comment by PC28K** [comment]
自分が認識しているAutoBreakの機能は保安装置ブロックを通過してから制限開始までの間に制限速度まで事前に減速させる機能であり、制限に引っかかってから制限速度を超過した場合制動になるのはOnOff関係ない仕様だと思いますが、この点勘違いしているのではないでしょうか

**Comment by PC28K** [comment]
![Screenshot_20240511-115505_Samsung Notes](https://github.com/Kai-Z-JP/ATSAssistMod/assets/41824434/e99863c6-abc8-4f94-bbb3-23af0bb133ad)
![Screenshot_20240511-115541_Samsung Notes](https://github.com/Kai-Z-JP/ATSAssistMod/assets/41824434/3ebb3ebe-6eeb-41dd-abbf-90527754ac21)

**Comment by useop0311** [comment]
ああ、間違って理解しました。 ありがとう
